from src.entities.base.blueprints import UnitBlueprint, CityBlueprint, CityImprovementBlueprint
from src.entities.game.units import Warrior, Cavalry, Archer, Crossbowman
from src.game_core.states.states import SelectingUnitState, UnitSelectedState, BuildingSelectedState
from src.terrains.game.terrains import GrassTerrain, SandTerrain, MountainTerrain

TERRAIN_NAME_MAPPING = {
    GrassTerrain: "grass",
    SandTerrain: "sand",
    MountainTerrain: "mountain",
}

TERRAIN_NAME_REVERSE_MAPPING = {v: k for k, v in TERRAIN_NAME_MAPPING.items()}

STATE_NAME_MAPPING = {
    SelectingUnitState: "selecting_unit_state",
    UnitSelectedState: "unit_selected_state",
    BuildingSelectedState: "building_selected_state",
}

STATE_NAME_REVERSE_MAPPING = {v: k for k, v in STATE_NAME_MAPPING.items()}

UNIT_BLUEPRINTS = {
    "warrior": UnitBlueprint(
        name="Воин",
        description="Базовый пехотный юнит ближнего боя, крепкий и надежный.",
        base_health=100,
        base_attack=25,
        attack_spread=5,
        attack_range=1,
        movement_range=3,
        cost_gold=50,
        cost_food=10,
        cost_metal=0,
        requirements=["barracks"],
        implementation_class=Warrior
    ),
    "cavalry": UnitBlueprint(
        name="Кавалерия",
        description="Быстрый и маневренный кавалерийский юнит, хорош для фланговых атак.",
        base_health=80,
        base_attack=45,
        attack_spread=7,
        attack_range=1,
        movement_range=5,
        cost_gold=80,
        cost_food=30,
        cost_metal=15,
        requirements=["stables"],
        implementation_class=Cavalry
    ),
    "archer": UnitBlueprint(
        name="Лучник",
        description="Дальнобойный юнит, эффективен на расстоянии, но уязвим в ближнем бою.",
        base_health=60,
        base_attack=20,
        attack_spread=8,
        attack_range=2,
        movement_range=2,
        cost_gold=60,
        cost_food=15,
        cost_metal=0,
        requirements=["archery_range"],
        implementation_class=Archer
    ),
    "crossbowman": UnitBlueprint(
        name="Арбалетчик",
        description="Дальнобойный юнит с повышенной точностью и пробивной силой.",
        base_health=70,
        base_attack=30,
        attack_spread=4,
        attack_range=3,
        movement_range=2,
        cost_gold=70,
        cost_food=18,
        cost_metal=10,
        requirements=["barracks", "workshop"],
        implementation_class=Crossbowman
    ),
}

CITY_BLUEPRINTS = {
    "city": CityBlueprint(
        name="Город",
        description="Главный город...",
        build_time=0,
        cost_gold=350,
        cost_wood=250,
        cost_stone=150,
        requirements=[],
        provides={},
        implementation_class="City",
        base_health=200,
        base_attack=15,
        min_damage=8,
        max_damage=40,
        defense=8,
        attack_range=4,
    ),
}

CITY_IMPROVEMENT_BLUEPRINTS = {
    "farm": CityImprovementBlueprint(
        name="Ферма",
        description="Увеличивает производство еды.",
        build_time=3,
        cost_gold=100,
        cost_wood=50,
        cost_stone=20,
        requirements=[],
        provides={"food_production": 8},
    ),
    "upgraded_farm": CityImprovementBlueprint(
        name="Продвинутая Ферма",
        description="Значительно увеличивает производство еды.",
        build_time=5,
        cost_gold=200,
        cost_wood=100,
        cost_stone=40,
        requirements=["farm"],
        provides={"food_production": 21},
    ),
    "farm_level_3": CityImprovementBlueprint(
        name="Ферма Уровень 3",
        description="Продвинутая ферма, значительно повышает производство еды.",
        build_time=7,
        cost_gold=300,
        cost_wood=150,
        cost_stone=60,
        requirements=["upgraded_farm"],
        provides={"food_production": 23},
    ),
    "mine": CityImprovementBlueprint(
        name="Шахта",
        description="Добывает ценные ресурсы.",
        build_time=4,
        cost_gold=120,
        cost_wood=30,
        cost_stone=80,
        requirements=[],
        provides={"gold_income": 20, "stone_income": 5},
    ),
    "mine_plus_1": CityImprovementBlueprint(
        name="Шахта +1",
        description="Улучшенная шахта, дающая небольшую прибавку к добыче металлов.",
        build_time=5,
        cost_gold=150,
        cost_wood=50,
        cost_stone=100,
        requirements=["mine"],
        provides={"gold_income": 5, "stone_income": 5, "metal_income": 2},
    ),
    "quarry": CityImprovementBlueprint(
        name="Каменоломня",
        description="Значительно увеличивает добычу камня.",
        build_time=5,
        cost_gold=150,
        cost_wood=50,
        cost_stone=100,
        requirements=["mine"],
        provides={"stone_income": 18},
    ),
    "quarry_plus_1": CityImprovementBlueprint(
        name="Каменоломня +1",
        description="Улучшенная каменоломня, дающая небольшую прибавку к добыче металлов.",
        build_time=5,
        cost_gold=150,
        cost_wood=50,
        cost_stone=100,
        requirements=["quarry"],
        provides={"stone_income": 5, "metal_income": 2},
    ),
    "metallurgy": CityImprovementBlueprint(
        name="Металлургия",
        description="Позволяет более эффективно добывать и перерабатывать металлы.",
        build_time=8,
        cost_gold=250,
        cost_wood=100,
        cost_stone=150,
        requirements=["quarry"],
        provides={"metal_income": 5},
    ),
    "barracks": CityImprovementBlueprint(
        name="Казармы",
        description="Позволяет нанимать пехотные юниты.",
        build_time=5,
        cost_gold=150,
        cost_wood=70,
        cost_stone=0,
        requirements=[],
        provides={},
    ),
    "stables": CityImprovementBlueprint(
        name="Конюшня",
        description="Позволяет нанимать кавалерию.",
        build_time=6,
        cost_gold=200,
        cost_wood=150,
        cost_stone=50,
        requirements=["barracks"],
        provides={},
    ),
    "archery_range": CityImprovementBlueprint(
        name="Стрельбище",
        description="Позволяет нанимать лучников.",
        build_time=5,
        cost_gold=150,
        cost_wood=100,
        cost_stone=20,
        requirements=[],
        provides={},
    ),
    "workshop": CityImprovementBlueprint(
        name="Мастерская",
        description="Позволяет нанимать арбалетчиков.",
        build_time=7,
        cost_gold=250,
        cost_wood=120,
        cost_stone=80,
        requirements=["barracks"],
        provides={},
    ),
    "market": CityImprovementBlueprint(
        name="Рынок",
        description="Увеличивает доход золота.",
        build_time=4,
        cost_gold=150,
        cost_wood=80,
        cost_stone=20,
        requirements=[],
        provides={"gold_income": 15},
    ),
    "temple": CityImprovementBlueprint(
        name="Храм",
        description="Повышает оборону города.",
        build_time=6,
        cost_gold=180,
        cost_wood=50,
        cost_stone=120,
        requirements=[],
        provides={"city_defense_bonus": 5},
    ),
    "fort": CityImprovementBlueprint(
        name="Форт",
        description="Укрепленное сооружение, повышающее обороноспособность города.",
        build_time=6,
        cost_gold=200,
        cost_wood=100,
        cost_stone=200,
        requirements=["barracks"],
        provides={"city_defense_bonus": 5},
    ),
    "armory": CityImprovementBlueprint(
        name="Оружейная",
        description="Место, где изготавливается и улучшается оружие, повышает атаку города.",
        build_time=7,
        cost_gold=250,
        cost_wood=100,
        cost_stone=100,
        cost_metal=100,
        requirements=["workshop", "metallurgy"],
        provides={"city_attack_bonus": 5},
    ),
    "walls": CityImprovementBlueprint(
        name="Стены",
        description="Значительно повышают защиту города.",
        build_time=10,
        cost_gold=300,
        cost_wood=200,
        cost_stone=300,
        requirements=["fort"],
        provides={"city_defense_bonus": 10},
    ),
}
